/*
 * This source file was generated by the Gradle 'init' task
 */
package mtchs.backupTracker;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void shouldAnswerWithTrue() {
        assertTrue(true);
    }
}
