/*
 * This source file was generated by the Gradle 'init' task
 */
package mtchs.backupTracker;

import java.io.File;

import org.json.JSONArray;
import org.json.JSONObject;

import mtchs.backupTracker.backupEngine.BackupEngine;
import mtchs.backupTracker.backupEngine.FileHasher;

/**
 * App is the main entry point for the Backup Tracker application. It currently only supports a version flag to display the application version.
 * 
 * @author Carsen Gafford
 * @version 0.1.0
 * @since 04-13-2026
 */
public class App {
    public static void main(String[] args) {
        
        if (args.length == 0) {
            System.out.println("No arguments provided");
        }
        
        if (args[0].equals("-v") || args[0].equals("--version") && args.length == 1) {
            System.out.println("Backup Tracker Version 0.0.3");
        } else if (args[0].equals("-track") || args[0].equals("-t") && args.length == 3) {
            BackupEngine backupEngine = new BackupEngine();
            LocalTracker tracker = new LocalTracker();
            File fileToTrack = new File(args[1]);

            if (fileToTrack.isDirectory()) {
                tracker.trackFolder(fileToTrack);
            } else if (fileToTrack.isFile()) {
                tracker.trackFile(fileToTrack);
            }
            String backupPath = backupEngine.backup(args[1], args[2]);
            if (backupPath != null) {
                tracker.setBackupPath(args[1], backupPath);
            }

            System.out.println("File/Folder tracked and backed up successfully");
        } else if (args[0].equals("-update") || args[0].equals("-u") && args.length == 1) {
            BackupEngine backupEngine = new BackupEngine();
            LocalTracker tracker = new LocalTracker();
            FileHasher hasher = new FileHasher();
            
            JSONArray trackedItems = tracker.getTrackedItems();
            System.out.println("Updating backups... [0%]");
            for (int i = 0; i < trackedItems.length(); i++) {
                JSONObject item = trackedItems.getJSONObject(i);
                String type = item.getString("type");
                String sourcePath = item.getString("sourcePath");
                if (item.isNull("backupPath")) {
                    System.out.println("No backup path for " + sourcePath + ", skipping.");
                    continue;
                }
                String backupPath = item.getString("backupPath");
                System.out.println("Updating item " + (i+1) + "/" + trackedItems.length() + ": " + sourcePath);
                backupEngine.updateBackup(type, sourcePath, backupPath, hasher);
                int percent = (int) (((i + 1) * 100) / trackedItems.length());
                System.out.print("\rUpdating backups... [" + percent + "%]");
            }
            System.out.println("\rUpdating backups... [100%]");
            System.out.println("Update completed.");
        } else if (args[0].equals("-backup") || args[0].equals("-b") && args.length == 3) {
            BackupEngine backupEngine = new BackupEngine();
            String backupPath = backupEngine.backup(args[1], args[2]);
            if (backupPath != null) {
                System.out.println("Backup completed successfully: " + backupPath);
            } else {
                System.out.println("Backup failed.");
            }
        } else if (args[0].equals("-help") || args[0].equals("-h")) {
            System.out.println("Usage:");
            System.out.println("  -v, --version                Display the application version");
            System.out.println("  -track, -t <source> <dest>   Track a file or folder and back it up to the specified destination");
            System.out.println("  -update, -u                  Update all tracked items by re-backing them up if they have changed");
            System.out.println("  -backup, -b <source> <dest>  Perform a backup of the specified source to the destination folder");
            System.out.println("  -help, -h                    Display this help message");
        } else {
            System.out.println("Invalid arguments. Use -help for usage information.");
        }
    }
}
