/*
 * This source file was generated by the Gradle 'init' task
 */
package mtchs.backupTracker;

import java.io.File;

import org.json.JSONArray;
import org.json.JSONObject;

import mtchs.backupTracker.backupEngine.BackupEngine;
import mtchs.backupTracker.backupEngine.FileHasher;

/**
 * App is the main entry point for the Backup Tracker application. It currently only supports a version flag to display the application version.
 * 
 * @author Carsen Gafford
 * @version 0.0.3
 * @since 04-06-2026
 */
public class App {
    public static void main(String[] args) {
        
        if (args.length == 0) {
            System.out.println("No arguments provided");
        }
        
        if (args[0].equals("-v") && args.length == 1) {
            System.out.println("Backup Tracker Version 0.0.3");
        } else if (args[0].equals("-track") && args.length == 3) {
            BackupEngine backupEngine = new BackupEngine();
            LocalTracker tracker = new LocalTracker();
            File fileToTrack = new File(args[1]);

            if (fileToTrack.isDirectory()) {
                tracker.trackFolder(fileToTrack);
            } else if (fileToTrack.isFile()) {
                tracker.trackFile(fileToTrack);
            }
            String backupPath = backupEngine.backup(args[1], args[2]);
            if (backupPath != null) {
                tracker.setBackupPath(args[1], backupPath);
            }

            System.out.println("File/Folder tracked and backed up successfully");
        } else if (args[0].equals("-update") && args.length == 1) {
            BackupEngine backupEngine = new BackupEngine();
            LocalTracker tracker = new LocalTracker();
            FileHasher hasher = new FileHasher();
            
            JSONArray trackedItems = tracker.getTrackedItems();
            for (int i = 0; i < trackedItems.length(); i++) {
                JSONObject item = trackedItems.getJSONObject(i);
                String type = item.getString("type");
                String sourcePath = item.getString("sourcePath");
                if (item.isNull("backupPath")) {
                    System.out.println("No backup path for " + sourcePath + ", skipping.");
                    continue;
                }
                String backupPath = item.getString("backupPath");
                backupEngine.updateBackup(type, sourcePath, backupPath, hasher);
            }
            System.out.println("Update completed.");
        }
    }
}
