/*
 * This source file was generated by the Gradle 'init' task
 */
package mtchs.backupTracker;

import java.io.File;

import mtchs.backupTracker.backupEngine.BackupEngine;
import mtchs.backupTracker.backupEngine.FileHasher;

public class App {
    public static void main(String[] args) {
        FileHasher hasher = new FileHasher();

        String out = hasher.hashFile("C:\\Gradle\\gradle-9.4.1\\bin\\gradle.bat");
        System.out.println(out);
    }
}
